//
// Created by simeon on 6/22/26.
//

#ifndef CONSOLE_IMAGE_EDITOR_TRANSFORMATION_H
#define CONSOLE_IMAGE_EDITOR_TRANSFORMATION_H


class Transformation {
};


#endif //CONSOLE_IMAGE_EDITOR_TRANSFORMATION_H
