//
// Created by simeon on 6/22/26.
//

#ifndef CONSOLE_IMAGE_EDITOR_TRANSFORMATIONTYPE_H
#define CONSOLE_IMAGE_EDITOR_TRANSFORMATIONTYPE_H

enum class TransformationType : char{
    UNKNOWN = -1,

    ROTATE_RIGHT,
    ROTATE_LEFT,
    FLIP_TOP,
    FLIP_LEFT,

    GRAYSCALE,
    MONOCHROME,
    NEGATIVE,

    TRANSFORMATION_TYPE_COUNT
};

#endif //CONSOLE_IMAGE_EDITOR_TRANSFORMATIONTYPE_H
