#ifndef CONSOLE_IMAGE_EDITOR_CUSTOMEXCEPTIONS_H
#define CONSOLE_IMAGE_EDITOR_CUSTOMEXCEPTIONS_H

enum class CustomExceptions {
    INCOMPATIBLE_ACTION_TYPES,
    ACTION_TYPE_NOT_FILTER,
    ACTION_TYPE_IS_FILTER
};

#endif //CONSOLE_IMAGE_EDITOR_CUSTOMEXCEPTIONS_H
